import "./globals.css";
import { Inter } from "next/font/google";
import { StarknetProvider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "OpenGen",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/favicon.ico" />
                <title>OpenGen</title>
            </head>
            <body className={inter.className}>
                <StarknetProvider>{children}</StarknetProvider>
            </body>
        </html>
    );
}
